(PA-6897) Bump voxpupuli-rubocop
Earlier versions of voxpupuli-rubocop resolve to rubocop-factory_bot 2.26.0 that
causes this error:

```
$ bundle exec rubocop
Error: Property AutoCorrect of cop FactoryBot/CreateList is supposed to be a boolean and contextual is not
```

See https://github.com/rubocop/rubocop-rspec/issues/1916

Update to newer voxpupuli-rubocop to avoid this issue.